version: '3.8'

services:
  tomcat:
    image: tomcat:8
    volumes:
      - ./target/student.war:/usr/local/tomcat/webapps/student.war
      - ./target/mysql-connector.jar:/usr/local/tomcat/lib/mysql-connector.jar
      - ./data.txt:/usr/local/tomcat/data.txt
    ports:
      - "8080:8080"
    command: sh -c "cp /usr/local/tomcat/data.txt /tmp/data.txt && sed -i '21,24d' /usr/local/tomcat/conf/context.xml && sed -i '20r /tmp/data.txt' /usr/local/tomcat/conf/context.xml"
