version: "3.9"
services:
  tomcat:
    build: ./tomcat
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    build: ./mysql
    environment:
      MYSQL_DATABASE: studentapp
      MYSQL_ROOT_PASSWORD: Admin123
    volumes:
      - ./mysql:/var/lib/mysql
    command: ["/bin/bash", "-c", "service mysql start && tail -f /dev/null"]
