version: '3.9'

services:
  tomcat:
    build: ./tomcat
    ports:
      - "8081:8080"
    depends_on:
      - db

  db:
    build: ./mysql
    environment:
      MYSQL_ROOT_PASSWORD: Admin123
      MYSQL_DATABASE: studentapp
    volumes:
      - ./mysql/data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
